### ISSUE TITLE
suggestion: match partial phone number

### ISSUE THREAD

**Issue by korakinos** [erik-perri/android-call-filter#1]
Right now, Match rules only apply if the provided string matches the entire caller number. I suggest matching partial numbers as well by replacing the call to String.equal() with String.contains() in MatchRuleHandler.java .

Use case: Be available (or to the contrary, unavailable) to a set of callers sharing one telephone system, like calls from a company building or a government agency.

By the way, thanks a lot for this code! it's almost exactly what I was looking for, I even installed Android Studio just to be able to run it. Are you planning to publish the app on F-Droid?

**Comment by korakinos** [comment]
Like this:

https://github.com/korakinos/android-call-filter/commit/896a63778e3a397f13333d406dbaeae6104da4e6

Alternatively, glob/wildcard-style matches would also work.

**Comment by erik-perri** [comment]
I added the ability to apply wildcards to a match, let me know if that works for you.  If no wildcard is added to the match it falls back to an exact match.  I would be fine changing it to fall back to a wildcard match, like your commit, but would want to add another match type option for exact matches if so. If you think that is worth doing let me know.

I did not have any plans on publishing it to an app store, I felt that would imply a level of support I am not able to offer.  I am not primarily an Android developer and only have 1 phone and the emulator to test with.

**Comment by korakinos** [comment]
This is great, thanks! You are probably right that it should stay possible to check for exact matches. And I think it makes sense to have wildcard and exact match as the same type, like you implemented, and not as two separate rule types. That way there is no possibility to select the wrong one by mistake. The only downside to me is that for simple "contains" use I have to type two extra asterisks, and I can live with that.

About publishing and support – fair point! I'll just stick to building this app myself, then.
