### ISSUE TITLE
Works !!

### ISSUE THREAD

**Issue by dayeggpi** [erik-perri/android-call-filter#3]
Just wanted to post a message to mention that I have been searching a solution that allows me to filter/block a list of numbers starting with certain digits, and NONE worked, except yours.
I am not a developer, but was able to install Android Studio, import your project, build it, and install the apk on my device in 10minutes.

It works great.

Thank you for your help and time in developing this !

**Comment by erik-perri** [comment]
I am glad to hear it worked for you and wasn't too much trouble to get setup.

**Comment by adudu21isme** [comment]
Can confirm it works too!
I was receiving empty calls each day from random phone numbers so i found this, got android studio, imported the repo, modified some stuff so i can build APK without it erroring, installed it onto my phone with ADB and now i can see that they get automatically blocked without noticing manually which is pretty good!
